use std::io::Write;

/// Embed the vendored ISPDB snapshot as a compile-time table.
///
/// Generates `ispdb_table.rs` — a sorted `&[(&str, &str)]` of (domain, XML)
/// pairs, each value an `include_str!` so the bytes land in the binary and the
/// file list is verified at compile time.
///
/// Deliberately NOT the `include_dir` crate: this is ~30 lines, and keeping a
/// dependency off a product whose licence surface has to stay auditable is
/// worth more than the convenience.
fn embed_ispdb() {
    let manifest = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR");
    let dir = std::path::Path::new(&manifest).join("resources/ispdb");

    // Re-run when a config is added, removed, or refreshed by sync-ispdb.sh.
    println!("cargo:rerun-if-changed=resources/ispdb");

    let mut entries: Vec<(String, String)> = Vec::new();
    if let Ok(read) = std::fs::read_dir(&dir) {
        for entry in read.flatten() {
            let path = entry.path();
            if path.extension().and_then(|e| e.to_str()) != Some("xml") {
                continue;
            }
            let Some(stem) = path.file_stem().and_then(|s| s.to_str()) else {
                continue;
            };
            // The filename IS the domain (`gmx.net.xml` -> `gmx.net`).
            entries.push((stem.to_ascii_lowercase(), path.display().to_string()));
        }
    }
    // Sorted so the table can be binary-searched, and so the generated file is
    // reproducible — `read_dir` order is not guaranteed across machines.
    entries.sort();

    let out =
        std::path::Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("ispdb_table.rs");
    let mut f = std::fs::File::create(&out).expect("create ispdb_table.rs");
    writeln!(f, "// @generated by build.rs — do not edit").unwrap();
    writeln!(f, "pub static ISPDB: &[(&str, &str)] = &[").unwrap();
    for (domain, path) in &entries {
        writeln!(f, "    ({domain:?}, include_str!({path:?})),").unwrap();
    }
    writeln!(f, "];").unwrap();
}

fn main() {
    embed_ispdb();
}
